### ISSUE TITLE
[Bug]: Reanimated actors use swimming state/idle with behaviours generated on v2.0.4 and higher

### ISSUE THREAD

**Issue by HanJoJ** [Monitor221hz/Pandora-Behaviour-Engine-Plus#295]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.6.3-alpha, v2.0.4-alpha, v2.1.5-alpha, v2.3.0-beta

### Provide Instructions on Reproducing the Problem

This is kind of a weird case and might be caused by another mod in conjunction with Pandora (I'm not even sure if every of the .. you know which.. mods is even supported), however I found out, that this only happens with the versions later than v1.6.3-alpha. (Might not be true for every version, but was for any following version I tried)
With said version the reanimation works as intended, with the tested versions afterwards (2.0.4, 2.1.5 and 2.3.0) any reanimated **Human** will revive in a swimming (in air) state (including the swimming audio). Additionally OAR will replace this animation with an alternative swimming animation, just like the game is assuming the NPC is in the water.

The output (MO2 separate mod folder) was cleared after a new version of Pandora was installed and run.
Any animation mod directly aimed at the reanimation animation (e.g. Faster Reanimation) was temporarily disabled on the newer versions, without any change in the outcome. Using `sae IdleForceDefaultState` does fix this for a reanimated corpse temporarily. Any newly reanimated npc will start "swimming" again.
Additionally, the newly generated output was also tested on a new save without any change.

In the log for 2.1.5 there are various occurences of
`WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File >`
as well as some IndexOutOfRange Errors
```WARN : FNIS Parser > Serialize > Animlist > FNIS_Kudasai_List.txt > FAILED > System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Pandora.Patch.Patchers.Skyrim.FNIS.FNISAnimationFactory.CreateFromLine(String animRoot, String line, IFNISAnimation& animation) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\PandoraPlus\MVVM\Model\Patch\Patchers\Skyrim\FNIS\FNISAnimationFactory.cs:line 81
   at Pandora.Patch.Patchers.Skyrim.FNIS.FNISAnimationList.FromFile(FileInfo file) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\PandoraPlus\MVVM\Model\Patch\Patchers\Skyrim\FNIS\FNISAnimationList.cs:line 95
   at Pandora.Patch.Patchers.Skyrim.FNIS.FNISParser.ParseAnimlistFolder(DirectoryInfo folder, Project project, ProjectManager projectManager) in D:\a\Pandora-Behaviour-Engine-Plus\Pandora-Behaviour-Engine-Plus\PandoraPlus\MVVM\Model\Patch\Patchers\Skyrim\FNIS\FNISParser.cs:line 176
```
which are both not present in the logs of the older version. (Full logs attached in the output zip files for 1.6.3 and 2.1.5)

I'm not sure if they are still required, but XPMSE patches which were attached to earlier releases are still enabled:
- Pandora.XPMSE.AIO.Universal.Patch.v1.0.0-alpha-dev
- Pandora.XPMSE.Patch.v1.1.3.Universal

When I ran the generation with version 1.6.3 and copied over the files from 2.1.5 the issue did not appear. However I'd prefer to properly generate the actual output on the current version, especially since you stated on one of the releases that this should not be done to begin with.

The actual steps I did (before I tried to find the reason for the issue):
1. Used v1.6.3 to generate files (with the 2 patches mentioned above) - Reanimating NPCs is working fine
3. Installed v2.0.4, cleared the Pandora Output folder completely.
4. Swapped the executable on MO2 to run the newer version and reenabled all the patches inside Pandora
5. Regenerated the behaviours with the newer version (still using the 2 patches) - did not reanimate NPC for some time so didn't notice anything about it.
6. Installed v.2.1.5, cleared the Pandora Output folder completely again
7. Repeated step 3+4 with the new version
8. Jumped ingame and reanimated a corpse -> swimming animation. 
9. Assumed OAR conditions to be the cause which turned out false
10. Cleared the output and regenerated the behaviours with different verisons multiple times 

Like I wrote in the beginning I'm not sure if this is an actual bug of Pandora , but if its not I was hoping that you have an idea what is causing this.

Thank you in advance.

### Provide Relevant Files

[Pandora Output 1.6.3.zip](https://github.com/user-attachments/files/16754097/Pandora.Output.1.6.3.zip)
[Pandora Output 2.1.5.zip](https://github.com/user-attachments/files/16754098/Pandora.Output.2.1.5.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by HanJoJ** [comment]
Small addition:

I'm using Acheron and after I was downed and an event played out (dragon soul absorption) the PC was also using the swimming animation on land.
Unfortunately I don't know if this event is playing some kind of reanimation animation for the player too, as it sets a black screen before the "respawn". Before that the PC was using the default "downed" animation which was working fine.

**Comment by SeviiIsland** [comment]
I just wanna add that I also encountered this bug. But on top of the swimming idle there is also a random chance that the game just crashes for me, whenever an npc gets reanimated with a spell.

**Comment by nb097** [comment]
I was getting consistent CTDs any time a playable race NPC was reanimated on 2.3.0 and 2.1.5 (didn't try any further versions in the 2.x line). Rolling back to 1.6.3 resulted in the CTDs no longer happening.

**Comment by Monitor221hz** [comment]
Test on v2.3.5-alpha please.

**Comment by nb097** [comment]
Unfortunately still CTD-ing on reanimating a playable race (removed the meshes output from Pandora 1.6.3, regenerated with 2.3.5).

**Comment by Monitor221hz** [comment]
> Unfortunately still CTD-ing on reanimating a playable race (backed up and removed the meshes output from Pandora 1.6.3, regenerated with 2.3.5).

This is a separate problem, you need to start your own thread and post the relevant files there or I cannot narrow down the problem easily.

**Comment by nb097** [comment]
> This is a separate problem, you need to start your own thread and post the relevant files there or I cannot narrow down the problem easily.

Alright, will do. Thought they were related, hence posting here.

**Comment by MK99MA** [comment]
Hi @Monitor221hz,

thank you for the update. 
Unfortunately I'm still running into the issue after generating the files again with 2.3.6.
Old output was cleared just like before, however I might have added a few mods with animations since the issue was created.
One thing that did improve however (which I didn't report yet as I only noticed during recent tests) is that a crash that consistently happened when I tried to jump with 2 spells equipped did not happen any longer on this version. (This was also fine on 1.6.3)

Attached is the output folder and a video of a reanimated NPC recorded during the first bootup after regenerating the files.

[Output_2.3.6.zip](https://github.com/user-attachments/files/17510922/Output_2.3.6.zip)

https://github.com/user-attachments/assets/c9311f00-e05d-433d-b831-f4cd18f8ac5e

**Comment by HanJoJ** [comment]
Hi @Monitor221hz,

thank you for the update.
Unfortunately the issue still happens with version 2.3.6, see the attached video which was recorded after I regenerated the files with the new version.
Output was cleared before regenerating, however I'll try again to make sure.
One thing I did notice is that a reproducable crash (which I did not report yet) does not happen anymore. Before with behaviours generated with v 2.x.x+ equipping two spells and trying to jump would crash.

[Output_2.3.6.zip](https://github.com/user-attachments/files/17511069/Output_2.3.6.zip)
https://github.com/user-attachments/assets/4e9bba80-9de0-4946-bd6b-5e59df2f9a41

**Comment by HanJoJ** [comment]
Just wanted to confirm, that its still the same after clearing the old files before and regenerating it.

Additionally a video of the "whole process" though I'd assume it was already somewhat clear by the one before + the initial description.
https://github.com/user-attachments/assets/1b72be61-2175-41e3-a8a3-a3c34fe3cd44

**Comment by Monitor221hz** [comment]
Check v2.4.0-beta, the problem should be fixed if it's related to #331

**Comment by HanJoJ** [comment]
Hi @Monitor221hz,

unfortunately it seems like the cause is a different than the one in #331, as it still happens for me. Output folder was cleared before (I think you added a check for this anyway?)
Attached is the whole output folder as before. Somehow my video wasn't saved, if you want / need it I'll add it, but in essence it looks exactly the same as in the 2 videos above.

[Output_2.4.0.zip](https://github.com/user-attachments/files/17527194/Output_2.4.0.zip)

Additionally, with 2.4.0 the crash I mentioned above occured again, i attached the crashlog of it here, but if you want me to create an additional issue for it I'll gladly do so.

[Crash_2024_10_25_22-11-5.txt](https://github.com/user-attachments/files/17527225/Crash_2024_10_25_22-11-5.txt)

Also, just as a side-note, thank you for all your work on this, despite the issues I'm experiencing with some versions, I'd never go back to Nemesis X FNIS (which would be required for my setup..)

**Comment by HanJoJ** [comment]
Just as some kind of update. After trying some more stuff (including swapping around Pandora/Nemesis patches) the animation keeps happening. Additionally I noticed enemies _occasionally_ fleeing with a swimming animation after they got downed reached a very low HP state. Unfortunately it does not seem happen all the time and I did not find a consistent way to reproduce it.

Talking about consistent reproducing a problem, I'd also want to add that the crash mentioned above always happens as soon as I try to jump with raised hands while having equipped a spell in each hand. Testing the different setups did not seem to make a difference here either.

All of the last tests were done with 2.4.0-beta.

**Comment by Monitor221hz** [comment]
I will look more into this issue and try to reproduce this on my end. Does it persist on a bare bones setup (no behavior patches/FNIS mods except Pandora Base)?

**Comment by HanJoJ** [comment]
Hm, perhaps I missed some combinations? Neither of the issues I'm experiencing happened with a new profile where I disabled every Animation related I could find (some exceptions, like SexLab as its a requirement for alot of mods in my list and I wanted to keep it generally as close as possible to the real setup)
Eiter way, Jumping with Spells in both hands didn't induce a CTD as well as reanimating an actor did not casue the swimming animation. 

Since I'm normally using two mods directly affecting jumping (Jump Behavior Overhaul & Jumping Attack) I might think that one of those or the comination of them could be the culprit for the CTD, though I was thinking that I disabled both of them during my tests before.
Either way, I'll do some more tests with only 1 patch being used each.


Patch was generated into a new output folder with this setup:
![image](https://github.com/user-attachments/assets/7241d7a9-a2ef-4385-b4db-442fb2a637db)

https://github.com/user-attachments/assets/33645f56-291d-4cb9-a21e-832c5d965074

**Comment by HanJoJ** [comment]
Another update @Monitor221hz :
After some more extensive testing, I think I found the culprit for the swimming animation, and it makes actually somewhat sense. Not only that its related to swimming, I think I might've missed it by earlier tests because the mod was in a wrong category on my MO2 setup (category with disabled stuff I kept for other saves).

UnderwaterCombat

The mirror I originally used to download it was skyrim-guild.com and I'm not sure if the file is available elsewhere so I attached it here. If this should be removed just give me a heads-up, alternatively you can remove this comment too.
I'd just assume investigating whats going on is a lot easier with the mod in question being available.

[UnderwaterCombat+Standalone.zip](https://github.com/user-attachments/files/17721975/UnderwaterCombat%2BStandalone.zip)
(I doubt there will be issues but for information sake: Filetype was changed manually from .rar to .zip so I could attach it here)

**Comment by HanJoJ** [comment]
Just going to comment to keep this issue open.
I actually swapped out both of the culprits for BFCO which includes both parts (though imo the implementation of a jump attack is worse than on the individual mod).

I still hope that you will find out whats going wrong with the patch generation when those 2 mods are involved, as this might also solve other issues / incompatibilities. (If this is at all something you can fix in Pandora).

**Comment by HanJoJ** [comment]
Hi @Monitor221hz ,
I'm not sure if it makes sense to attach it here or if it wouldn't be better to create a new issue, but I came across another thing with Pandora generated files. If I should create a new issue I'll gladly do so.

I saw that there were issues about the mod [Immersive Equipping Animations](https://www.nexusmods.com/skyrimspecialedition/mods/77187) before, however those were not related to crashs but animations not playing.
In my previous savegame (and I don't think I updated the mod itself in between) this issue did not occur, so it might not be related to the output to begin with, but disabling the use of those animation in the mods MCM or disabling the whole mod before generating the behaviours prevents the crash from happening.

When using above mod and including it in the generation process, whenever the animations to (un-)equip boots (unequipboots.hkx, equipboots.hkx) are supposed to play for the player character the game will CTD instantly. I can see the boots disappearing, just before the animation is supposed to start to play.

Crashlogs are also showing quite a few references to animation related files and like I wrote above, not using the animation files (either way) prevents the crash from happening.
[.NET Framework](https://github.com/user-attachments/files/18252439/Crash_2024_12_26_0-37-55.txt)
[CrashLoggerSSE](https://github.com/user-attachments/files/18252440/crash-2024-12-25-23-37-56.log)

The output (including the mod):
[Pandora Output.zip](https://github.com/user-attachments/files/18252453/Pandora.Output.zip)

Since it worked in the previous save while including it in the generation I'm not sure if its a general issue with Pandora, but maybe you can see whats causing this here. 

Thank you in advance.
